const CREATE = 'MEMBUAT';
const UPDATE = 'MENYUNTING';
const UPDATE_PASSWORD = 'MENYUNTING PASSWORD';
const DELETE = 'MENGHAPUS';
const PRINT = 'MENCETAK / MENGUNDUH';
const LOAN = 'PEMINJAMAN';

const DOCUMENT = 'DOKUMEN';
const REPORT = 'LAPORAN';
const CATEGORY = 'KATEGORI DOKUMEN';
const USER = 'PENGGUNA';
const DOCUMENT_PHISYC = 'DOKUMEN FISIK';

module.exports = { CREATE, UPDATE, UPDATE_PASSWORD, DELETE, PRINT, LOAN, DOCUMENT, CATEGORY, USER, DOCUMENT_PHISYC, REPORT }