const CREATE = 'MEMBUAT';
const UPDATE = 'MENYUNTING';
const DELETE = 'MENGHAPUS';
const PRINT = 'MENCETAK / MENGUNDUH';
const LOAN = 'MEMINJAMKAN';

const DOCUMENT = 'DOKUMEN';
const CATEGORY = 'KATEGORI DOKUMEN';
const USER = 'PENGGUNA';
const DOCUMENT_PHISYC = 'DOKUMEN FISIK';

module.exports = { CREATE, UPDATE, DELETE, PRINT, LOAN, DOCUMENT, CATEGORY, USER, DOCUMENT_PHISYC }